### ISSUE TITLE
newbie question

### ISSUE THREAD

**Issue by jesmitty** [Diaoul/babelfish#25]
I can't get modules from babelfish to do anything. From python see:

>>from nltk.misc import babelfish  #this part works, did pip install bablefish

>>print babelfish.translate('cookbook', 'english', 'spanish') 
-------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-31-882b105c1643> in <module>()
----> 1 print babelfish.translate('cookbook', 'english', 'spanish')

AttributeError: 'module' object has no attribute 'translate'

>>import inspect
>>inspect.getmembers(babelfish, predicate=inspect.ismethod)
[]       # no modules loaded from babelfish.

**Comment by labrys** [comment]
@jesmitty This is not the same babelfish as in nltk.
